<?php
/**
 * @author: dengyun
 * @time: 2017/9/12 17:22
 */

namespace backend\services;


class Article extends \common\services\Article
{
    /**
     * @param $content
     * @return true
     */
    public function addContent($content)
    {
        $tags = $content['tags'];
        $content['summary'] = mb_substr(strip_tags($content['content']), 0, 100);
        unset($content['tags']);
        $content['user_id'] = \Yii::$app->user->id;
        if(!$this->load(['Content' => $content])){
            return false;
        }
        if(!empty($content['id'])){
            $this->id = $content['id'];
            $saveResult = $this->update();
        }else {
            $saveResult = $this->save();
        }
        if($saveResult){
            $contentId = $this->id;
            $tags = explode(',', $tags);
            $tagIdMaps = ArticleTag::addContentTags($tags, $contentId);
            $this->tags = array_flip($tagIdMaps);
        }
        return $saveResult;
    }

    /**
     * @param int $userId
     * @param int $page
     * @param int $size
     * @return array|\yii\db\ActiveRecord[]
     */
    public static function getList($userId, $page = 1, $size = 20)
    {
        $query = [
            'user_id' => $userId,
        ];
        return self::find()->where($query)->offset(($page - 1) * $size)->limit($size)->orderBy('id desc')->all();
    }

    public function beforeSave($insert)
    {
        if(empty($this->id)){
            $time = date('Y-m-d H:i:s');
            $this->create_time = $time;
            $this->update_time = $time;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}